# fly.toml file generated for fly-hiring-challenge on 2022-05-08T23:05:59-07:00

app = "fly-hiring-challenge"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/root"
  source = "data"

[[services]]
  internal_port = 2222
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    port = 2222
